/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dmesq' at '13/09/16 09:21' with Gradle 2.10
 *
 * @author dmesq, @date 13/09/16 09:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
